classes:
- service.grafana.client.single
parameters:
  grafana:
    client:
      enabled: true
      server:
        protocol: http
        host: ${_param:stacklight_monitor_address}
        port: 3000
        user: ${_param:grafana_user}
        password: ${_param:grafana_password}
      remote_data:
        engine: 'salt_mine'
      datasource:
        lma:
          type: influxdb
          host: ${_param:grafana_influxdb_host}
          port: ${_param:influxdb_port}
          user: lma
          password: ${_param:influxdb_stacklight_password}
          database: lma
          is_default: true
